#@ load("@ytt:overlay", "overlay")

#@overlay/match by=overlay.subset({"kind": "IstioOperator", "spec":"components"}),expects=1
---
#@overlay/match by=overlay.subset({"ingressGateways":{"name": "istio-ingressgateway"}}),expects=1
k8s:
  #@overlay/match expects=0
  overlays:
  - kind: Deployment
    name: istio-ingressgateway
    patches:
      - path: spec.replicas
        value: 10
  #@overlay/replace
  hpaSpec:
    minReplicas: 10
    maxReplicas: 10
  service:
    #@overlay/match missing_ok=True
    type: LoadBalancer
  #@overlay/match missing_ok=True
  resources:
    limits:
      cpu: "4"
      memory: 2Gi
    requests:
      cpu: "2"
      memory: 2Gi

#@overlay/match by=overlay.subset("pilot"),expects=1
k8s:
  #@overlay/match missing_ok=True
  replicaCount: 10
  #@overlay/match expects=0
  overlays:
    - kind: Deployment
      name: istiod
      patches:
        - path: spec.replicas
          value: 10
  #@overlay/replace
  hpaSpec:
    minReplicas: 10
    maxReplicas: 10

