platform: linux
image_resource:
  type: docker-image
  source:
    repository: relintdockerhubpushbot/cf-for-k8s-ci

inputs:
  - name: cf-k8s-networking-ci
  - name: cf-for-k8s

run:
  path: cf-k8s-networking-ci/ci/tasks/scale/scale-up-istio.sh

params:
