#@data/values
---
#! Default values for cf-k8s-networking.
#! This is a YTT-formatted file.
systemNamespace: cf-system
workloadsNamespace: cf-workloads

routecontroller:
  image: gcr.io/cf-networking-images/cf-k8s-networking/routecontroller@sha256:1f35ffa5cd0ccfc5fead47a60bada131d024ca5c6a87085d5ee32415e1a10834
  ingressSolutionProvider: contour

service:
  externalPort: 80

runningInKIND: false
