platform: linux
image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/cf-for-k8s-ci

inputs:
  - name: cf-k8s-networking

run:
  path: cf-k8s-networking/ci/tasks/team/create-community-chore.sh

params:
  TRACKER_TOKEN:
