platform: linux
image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/cf-for-k8s-ci

inputs:
  - name: cf-k8s-networking-ci
  - name: istio-release

run:
  path: cf-k8s-networking-ci/ci/tasks/team/create-istio-osm-story.sh

params:
  TRACKER_TOKEN:
