platform: linux

image_resource:
  type: docker-image
  source:
    repository: gcr.io/cf-routing/cf-k8s-networking/k8s-deploy

run:
  path: cf-k8s-networking-ci/ci/tasks/cf4k8s/create-pr.sh

params:
  GITHUB_KEY:
  BRANCH:
  GITHUB_TITLE:
  GITHUB_BODY:
