platform: linux
image_resource:
  type: docker-image
  source:
    repository: relintdockerhubpushbot/cf-for-k8s-ci

inputs:
  - name: cf-for-k8s
  - name: cf-k8s-networking-ci
  - name: env-metadata

run:
  path: cf-k8s-networking-ci/ci/tasks/cf4k8s/run-smoke-test.sh

params:
  FLAKE_ATTEMPTS:
